#error handling
BAD_REQUEST:
  code: "400"
  message: "Bad request"
UNAUTHORIZED:
  code: "401"
  message: "Authentication error"
NOT_FOUND:
  code: "404"
  message: "Resource not found"
METHOD_NOT_ALLOWED:
  code: "405"
  message: "Method not allowed"
NOT_ACCEPTABLE:
  code: "406"
  message: "Not acceptable"
UNSUPPORTED_MEDIA_TYPE:
  code: "415"
  message: "Unsupported media type"
NOT_IMPLEMENTED:
  code: "501"
  message: "Not Implemented"
INTERNAL_SERVER_ERROR:
  code: "500"
  message: "An unexpected error occurred while processing the request."
SERVICE_UNAVAILABLE:
  code: "503"
  message: "Service unavailable"
CONNECTIVITY:
  code: "503"
  message: "Service unavailable: Database connection failed."

#custom
TRANSACTION_NOT_FOUND:
  code: "404"
  message: "transaction ID not found."
QUERY_EXECUTION:
  code: "409"
  message: "Cannot process transaction"
NO_RECORDS_FOUND:
  code: "204"
  message: "No records found"